/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package point.of.sale.system;

import java.io.File;
import java.io.FileReader;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author tyk54
 */
public class SalePage extends javax.swing.JFrame {

    /**
     * Creates new form SalePage
     */
    public SalePage() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    private String cashierName;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        appleText = new javax.swing.JTextField();
        bananaText = new javax.swing.JTextField();
        cherryText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        totalText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jb1 = new javax.swing.JButton();
        jb2 = new javax.swing.JButton();
        appleCheck = new javax.swing.JCheckBox();
        bananaCheck = new javax.swing.JCheckBox();
        cherryCheck = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel1.setText("Sales Menu");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel2.setText("Item");

        appleText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appleTextActionPerformed(evt);
            }
        });

        jLabel5.setText("Total");

        totalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTextActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel6.setText("number to buy");

        jb1.setText("Calculate");
        jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1ActionPerformed(evt);
            }
        });

        jb2.setText("Buy");
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });

        appleCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        appleCheck.setText("Apple $3.00/bag");
        appleCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appleCheckActionPerformed(evt);
            }
        });

        bananaCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bananaCheck.setText("Banana $2.00/bag");

        cherryCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cherryCheck.setText("Cherry $5.00/bag");

        jButton2.setText("Check Inventory");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(appleCheck)
                            .addComponent(bananaCheck)
                            .addComponent(cherryCheck))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cherryText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bananaText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(appleText)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel5)
                        .addGap(29, 29, 29)
                        .addComponent(totalText, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jButton2)
                        .addGap(27, 27, 27)
                        .addComponent(jb1)
                        .addGap(28, 28, 28)
                        .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(appleText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(appleCheck))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bananaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bananaCheck)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cherryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cherryCheck))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(totalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb1)
                    .addComponent(jb2)
                    .addComponent(jButton2))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void appleTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appleTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appleTextActionPerformed

    private void totalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTextActionPerformed

    private void appleCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appleCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appleCheckActionPerformed

    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed
        // TODO add your handling code here:
        totalText.setText(this.totalCalc() + "");
    }//GEN-LAST:event_jb1ActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
        // TODO add your handling code here:
        int appleNum = 0,bananaNum = 0,cherryNum = 0;
        long appleNum_inv =0,bananaNum_inv = 0,cherryNum_inv = 0;

        if(appleCheck.isSelected()){
            if((appleText.getText().matches("\\D+")) || appleText.getText().equals("")){
                JOptionPane.showMessageDialog(null, "input invalid", "WARNING_MESSAGE",JOptionPane.WARNING_MESSAGE);
            }
            appleNum = Integer.parseInt(appleText.getText());
        }
        if(bananaCheck.isSelected()){
            if((bananaText.getText().matches("\\D+")) || bananaText.getText().equals("")){
                JOptionPane.showMessageDialog(null, "input invalid", "WARNING_MESSAGE",JOptionPane.WARNING_MESSAGE);
            }
            bananaNum = Integer.parseInt(bananaText.getText());
        }
        if(cherryCheck.isSelected()){
            if((cherryText.getText().matches("\\D+")) || cherryText.getText().equals("")){
                JOptionPane.showMessageDialog(null, "input invalid", "WARNING_MESSAGE",JOptionPane.WARNING_MESSAGE);
            }	
            cherryNum = Integer.parseInt(cherryText.getText());
        }

        this.writeTransaction(appleNum, bananaNum, cherryNum);
        JSONParser parser = new JSONParser();
        try {
			
                Object obj = parser.parse(new FileReader("/Users/hunk/Java WorkSpace/inventory/info.json"));	
		JSONObject jobj = (JSONObject)obj;	
                appleNum_inv = (long) jobj.get("apple");
		bananaNum_inv = (long) jobj.get("banana");
		cherryNum_inv = (long) jobj.get("cherry");
            }
        catch(Exception e) {e.printStackTrace();}
        
        appleNum_inv = appleNum_inv - appleNum;
        bananaNum_inv = bananaNum_inv - bananaNum;
        cherryNum_inv = cherryNum_inv - cherryNum;
        
        JsonWR inventoryChange = new JsonWR();
        inventoryChange.inventoryWrite(inventoryChange.json_obj(appleNum_inv, bananaNum_inv, cherryNum_inv));
    }//GEN-LAST:event_jb2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        InventoryList il = new InventoryList();
        il.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalePage().setVisible(true);
            }
        });
    }
    public void UpdateInventory(){
        
        
    }
    
    public void writeTransaction(int appleNum,int bananaNum,int cherryNum){
        File file = new File("/Users/hunk/Java WorkSpace/transaction");  
        File[] files = file.listFiles();  
	int  num = 100;
	for (File f:files)  
            {  
		if(Integer.parseInt(f.getName().substring(0, 3)) > num) {
                    num = Integer.parseInt(f.getName().substring(0, 3));
		}	
            }
        
        JsonWR jsonwriter = new JsonWR();
        jsonwriter.transactionWrite(jsonwriter.json_obj(appleNum, bananaNum, cherryNum),
        		"/Users/hunk/Java WorkSpace/transaction/", num+1);
    }
    
    public void writeInventory(){
        
    }
    public double totalCalc(){
        final double applePerBag = 3;
        final double bananaPerBag = 2;
        final double cherryPerBag = 5;
        double appleTotal = 0;
        double bananaTotal = 0;
        double cherryTotal = 0;
        if(appleCheck.isSelected()){
            if((appleText.getText().matches("\\D+")) || appleText.getText().equals("")){
                JOptionPane.showMessageDialog(null, "input invalid", "WARNING_MESSAGE",JOptionPane.WARNING_MESSAGE);
            }
            appleTotal = applePerBag * Double.parseDouble(appleText.getText());
        }
        if(bananaCheck.isSelected()){
            if((bananaText.getText().matches("\\D+")) || bananaText.getText().equals("")){
                JOptionPane.showMessageDialog(null, "input invalid", "WARNING_MESSAGE",JOptionPane.WARNING_MESSAGE);
            }
            bananaTotal = bananaPerBag * Double.parseDouble(bananaText.getText());
        }
        if(cherryCheck.isSelected()){
            if((cherryText.getText().matches("\\D+")) || cherryText.getText().equals("")){
                JOptionPane.showMessageDialog(null, "input invalid", "WARNING_MESSAGE",JOptionPane.WARNING_MESSAGE);
            }	
            cherryTotal = cherryPerBag * Double.parseDouble(cherryText.getText());
        }
        
        return  appleTotal + bananaTotal + cherryTotal;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox appleCheck;
    private javax.swing.JTextField appleText;
    private javax.swing.JCheckBox bananaCheck;
    private javax.swing.JTextField bananaText;
    private javax.swing.JCheckBox cherryCheck;
    private javax.swing.JTextField cherryText;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb2;
    private javax.swing.JTextField totalText;
    // End of variables declaration//GEN-END:variables
}
